name: 서버 신청
description: 서비스를 배포할 AWS 서버를 신청합니다.
title: "AWS 서버 대여 신청"
assignees:
  - noeulnight
  - pmh-only
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        서버를 대여받기 위한 정보를 아래에 입력하세요.
        > 문의: 2학년 1반 임태현
  - type: dropdown
    id: regist_year
    attributes:
      label: 입학년도
      description: 입학년도를 선택해 주세요.
      multiple: false
      options: 
        - 2021
        - 2022
        - 2023
        - 2024
    validations:
      required: true
  - type: input
    id: class_id
    attributes:
      label: 학번
      description: 학번을 입력해주세요. (4자리)
      placeholder: "ex. 2114"
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: 이름
      description: 이름을 입력해주세요.
      placeholder: "ex. 임태현"
  - type: textarea
    id: reason
    attributes:
      label: 서버의 운영 목적을 입력해주세요.
      description: 목적을 자세하게 기재하지 않으면 요청이 거부될 수 있습니다.
      placeholder: "ex. 2022 캡스톤 프로젝트 인력부족 팀 서비스 운영"
    validations:
      required: true
  - type: input
    id: port
    attributes:
      label: 서버에 필요한 포트를 입력해주세요.
      description: 콤마(,)를 기준으로 포트를 작성해주세요. SSH(22)는 기본적으로 추가됩니다.
      placeholder: "ex. 80,443,3306"
    validations:
      required: true
  - type: dropdown
    id: ami
    attributes:
      label: 사용할 운영체제를 선택하세요.
      multiple: false
      options:
        - label: Ubuntu (Default)
        - label: AmazonLinux (CentOS)
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: 서버에 대한 정보를 받을 이메일을 입력하세요.
      description: 서버 인증키 파일과 가이드를 전송해드립니다.
      placeholder: "ex. school@litmaehyun.dev"
    validations:
      required: true
  - type: checkboxes
    id: check
    attributes:
      label: 이용 동의
      description: 본인은 해당 서버를 대여하면서 불법적이거나 서버에 피해가 갈수있는 서비스는 운영하지 않겠습니다.
      options:
      - label: 동의
        required: true
  - type: markdown
    attributes:
      value: |
        대여 신청 시 최대 3일 이내로 처리됩니다.
        3일 후에도 처리되지 않을 경우 아래 연락처로 문의해주세요
        - 2학년 1반 임태현
        - 2학년 2반 박민혁
        - 진창훈 선생님 (3층 교무실)
