name: approve
on:
  workflow_dispatch:
    types: [approve-command]
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.client_payload.issue.number }} 
          body: |
            Action started.
      - name: Install dependency
        run: |
          cd actions/approve
          npm i
      - name: Create Instance
        run: |
          cd actions/approve
          node . '${{ toJSON(github.event.client_payload.issue.body) }}' ${{ github.event.client_payload.args.named.name }}

      