name: approve
on:
  repository_dispatch:
    types: [approve-command]
jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          cd actions/approve
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Install dependency
        run: |
          cd actions/approve
          npm i
      - name: Create Instance
        id: create
        run: |
          cd actions/approve
          node . '${{ toJSON(github.event.client_payload.github.payload.issue.body) }}' ${{ github.event.client_payload.slash_command.args.named.id }} 
      - name: Test
        run: |
          echo ${{ steps.create.outputs.key }}
          echo ${{ steps.create.outputs.eip }}
